/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
    package Vista;
    import java.util.*;
    import javax.swing.*;

/**
 *
 * @author juan_
 */
    public class VistaCiudad extends javax.swing.JFrame {
    // variable  y estructura de los datos
    private DefaultListModel<String> modeloCiudades = new DefaultListModel<>();
    private DefaultListModel<String> modeloPaises = new DefaultListModel<>();
    private Map<String, String> ciudadPais = new HashMap<>();

// Relación entre ciudad y país
   

    /**
     * creo nueva forma en vista ciudad
     */
    public VistaCiudad() {
        
    initComponents();
    inicializar();
}

        private void inicializar() {
    // Datos iniciales
    ciudadPais.put("Madrid", "España");
    ciudadPais.put("París", "Francia");
    ciudadPais.put("México D.F.", "México");

    for (String ciudad : ciudadPais.keySet()) {
        modeloCiudades.addElement(ciudad);
    }

    jListCiudades.setModel(modeloCiudades);
    jListPaises.setModel(modeloPaises);

    // Cuando seleccionas una ciudad, muestra su país
    jListCiudades.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            String ciudad = jListCiudades.getSelectedValue();
            modeloPaises.clear();
            if (ciudad != null) {
                modeloPaises.addElement(ciudadPais.get(ciudad));
            }
        }
    });

    // Botón Crear
    btnCrear.addActionListener(e -> {
        String ciudad = JOptionPane.showInputDialog("Nombre de la ciudad:");
        if (ciudad != null && !ciudad.isEmpty()) {
            String pais = JOptionPane.showInputDialog("País de la ciudad:");
            if (pais != null && !pais.isEmpty()) {
                ciudadPais.put(ciudad, pais);
                modeloCiudades.addElement(ciudad);
            }
        }
    });

    // Botón Editar
    btnEditar.addActionListener(e -> {
        String seleccion = jListCiudades.getSelectedValue();
        if (seleccion == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una ciudad para editar");
            return;
        }
        String nuevaCiudad = JOptionPane.showInputDialog("Nuevo nombre:", seleccion);
        String nuevoPais = JOptionPane.showInputDialog("Nuevo país:", ciudadPais.get(seleccion));
        if (nuevaCiudad != null && nuevoPais != null) {
            ciudadPais.remove(seleccion);
            ciudadPais.put(nuevaCiudad, nuevoPais);
            modeloCiudades.removeElement(seleccion);
            modeloCiudades.addElement(nuevaCiudad);
        }
    });
}

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtrasCuidad = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        txtCiudad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCiudades = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPaises = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 450));

        btnAtrasCuidad.setText("Atras");
        btnAtrasCuidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCuidadActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");

        btnCrear.setText("Crear");

        txtCiudad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(255, 255, 255));
        txtCiudad.setText("Cuidad");

        jListCiudades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Paises " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCiudades);

        jListPaises.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ciudad" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListPaises);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtrasCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 464, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnAtrasCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasCuidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCuidadActionPerformed
        // TODO add your handling code here:
         VistaMenuPrincipal vista = new VistaMenuPrincipal ();
       vista.setVisible(true);
       // se crea metodo para retroceder (atras) en la pagina
       this.dispose();
    }//GEN-LAST:event_btnAtrasCuidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCiudad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCuidad;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JList<String> jListCiudades;
    private javax.swing.JList<String> jListPaises;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtCiudad;
    // End of variables declaration//GEN-END:variables
}


